# .pre-commit-config.yaml
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: fix-encoding-pragma


  - repo: https://github.com/DariuszPorowski/chatgpt-pre-commit-hooks
    rev: v0.1.3
    hooks:
      - id: chatgpt-commit-message
        args:
          - "--hook"
          - "chatgpt-commit-message"
          - "--max-char-count"
          - "1000"
          - "--description"

  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args: ['--global-config', '.pep8', '-v']


  # - repo: https://github.com/psf/black
  #   rev: 23.11.0
  #   hooks:
  #     - id: black
  #       args: ['--config', '.black', '--diff']

  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: v3.0.0a5
  #   hooks:
  #     - id: pylint
  #       args: ["--rcfile=.pylintrc", "--output-format=colorized"]
  #       files: .py$

  - repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
        args: ['--config', '.flake8', '-v']
        additional_dependencies: ['flake8-docstrings', 'flake8-docstrings-complete']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ['--verbose']
